// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accesstoken.sql

package db

import (
	"context"
)

const getAccessTokenByAccessKey = `-- name: GetAccessTokenByAccessKey :one
SELECT id, user_name, access_key, secret_key, describe, created_at, updated_at, deleted_at
FROM access_tokens
WHERE access_key = $1
`

func (q *Queries) GetAccessTokenByAccessKey(ctx context.Context, accessKey string) (AccessToken, error) {
	row := q.db.QueryRowContext(ctx, getAccessTokenByAccessKey, accessKey)
	var i AccessToken
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.AccessKey,
		&i.SecretKey,
		&i.Describe,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAccessTokenByAccessKeyAndSecretKey = `-- name: GetAccessTokenByAccessKeyAndSecretKey :one
SELECT id, user_name, access_key, secret_key, describe, created_at, updated_at, deleted_at
FROM access_tokens
WHERE access_key = $1 AND secret_key = $2
`

type GetAccessTokenByAccessKeyAndSecretKeyParams struct {
	AccessKey string
	SecretKey string
}

func (q *Queries) GetAccessTokenByAccessKeyAndSecretKey(ctx context.Context, arg GetAccessTokenByAccessKeyAndSecretKeyParams) (AccessToken, error) {
	row := q.db.QueryRowContext(ctx, getAccessTokenByAccessKeyAndSecretKey, arg.AccessKey, arg.SecretKey)
	var i AccessToken
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.AccessKey,
		&i.SecretKey,
		&i.Describe,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
