// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type AccessToken struct {
	ID        int64
	UserName  interface{}
	AccessKey interface{}
	SecretKey interface{}
	Describe  sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type Token struct {
	ID           int64
	UserID       interface{}
	ClientID     interface{}
	ClientSecret interface{}
	Domain       interface{}
	Public       int64
	Describe     sql.NullString
	RedirectUris sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    sql.NullTime
}

type User struct {
	ID             int64
	Username       interface{}
	HashedPassword []byte
	Email          interface{}
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      sql.NullTime
}
