// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type AccessToken struct {
	ID          interface{}
	UserName    string
	AccessKey   string
	SecretKey   string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
}

type Token struct {
	ID           interface{}
	UserID       string
	ClientID     string
	ClientSecret string
	Domain       string
	Public       int64
	Description  sql.NullString
	RedirectUris sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    sql.NullTime
}

type User struct {
	ID             interface{}
	Username       string
	HashedPassword []byte
	Email          sql.NullString
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      sql.NullTime
}
