// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: token.sql

package db

import (
	"context"
	"database/sql"
)

const createToken = `-- name: CreateToken :exec
INSERT INTO tokens (user_id, client_id, client_secret, domain, public, describe, redirect_uris, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, datetime('now'), datetime('now'))
`

type CreateTokenParams struct {
	UserID       interface{}
	ClientID     interface{}
	ClientSecret interface{}
	Domain       interface{}
	Public       int64
	Describe     sql.NullString
	RedirectUris sql.NullString
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) error {
	_, err := q.db.ExecContext(ctx, createToken,
		arg.UserID,
		arg.ClientID,
		arg.ClientSecret,
		arg.Domain,
		arg.Public,
		arg.Describe,
		arg.RedirectUris,
	)
	return err
}

const deleteToken = `-- name: DeleteToken :exec
DELETE FROM tokens
WHERE client_id = ?
`

func (q *Queries) DeleteToken(ctx context.Context, clientID interface{}) error {
	_, err := q.db.ExecContext(ctx, deleteToken, clientID)
	return err
}

const getTokenByClientID = `-- name: GetTokenByClientID :one
SELECT id, user_id, client_id, client_secret, domain, public, describe, redirect_uris, created_at, updated_at, deleted_at
FROM tokens
WHERE client_id = ?
`

func (q *Queries) GetTokenByClientID(ctx context.Context, clientID interface{}) (Token, error) {
	row := q.db.QueryRowContext(ctx, getTokenByClientID, clientID)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.ClientSecret,
		&i.Domain,
		&i.Public,
		&i.Describe,
		&i.RedirectUris,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTokenByID = `-- name: GetTokenByID :one
SELECT id, user_id, client_id, client_secret, domain, public, describe, redirect_uris, created_at, updated_at, deleted_at
FROM tokens
WHERE id = ?
`

func (q *Queries) GetTokenByID(ctx context.Context, id int64) (Token, error) {
	row := q.db.QueryRowContext(ctx, getTokenByID, id)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.ClientSecret,
		&i.Domain,
		&i.Public,
		&i.Describe,
		&i.RedirectUris,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTokensByDomain = `-- name: GetTokensByDomain :many
SELECT id, user_id, client_id, client_secret, domain, public, describe, redirect_uris, created_at, updated_at, deleted_at
FROM tokens
WHERE domain = ?
`

func (q *Queries) GetTokensByDomain(ctx context.Context, domain interface{}) ([]Token, error) {
	rows, err := q.db.QueryContext(ctx, getTokensByDomain, domain)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Token
	for rows.Next() {
		var i Token
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ClientID,
			&i.ClientSecret,
			&i.Domain,
			&i.Public,
			&i.Describe,
			&i.RedirectUris,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTokensByUserID = `-- name: GetTokensByUserID :many
SELECT id, user_id, client_id, client_secret, domain, public, describe, redirect_uris, created_at, updated_at, deleted_at
FROM tokens
WHERE user_id = ?
`

func (q *Queries) GetTokensByUserID(ctx context.Context, userID interface{}) ([]Token, error) {
	rows, err := q.db.QueryContext(ctx, getTokensByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Token
	for rows.Next() {
		var i Token
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ClientID,
			&i.ClientSecret,
			&i.Domain,
			&i.Public,
			&i.Describe,
			&i.RedirectUris,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRedirectURIs = `-- name: UpdateRedirectURIs :exec
UPDATE tokens
SET redirect_uris = ?, updated_at = datetime('now')
WHERE client_id = ?
`

type UpdateRedirectURIsParams struct {
	RedirectUris sql.NullString
	ClientID     interface{}
}

func (q *Queries) UpdateRedirectURIs(ctx context.Context, arg UpdateRedirectURIsParams) error {
	_, err := q.db.ExecContext(ctx, updateRedirectURIs, arg.RedirectUris, arg.ClientID)
	return err
}
