---
listenAddress: ":9096"
domain: "https://da-reg.duckdns.org"
logFile: "authserver.log"
dbFile: "authserver.db"
databaseType: postgresql
databaseURI: postgres://devops:devops@localhost/auth
sessionName: "authserver_session"
redis: "localhost:6379"
redisPassword: "Lxv-xw12dZhd=MxkN-wRt13"
redisDB: 0
origins:
  - "https://da-reg.duckdns.org"
