listenAddress: ":9096"
domain: "http://localhost"
logFile: "authserver_test.log"
dbFile: "/tmp/test_oauth_tokens"
databaseType: sqlite
databaseURI: "/tmp/test_authserver.db"
sessionName: "test_session"
redis: ""
redisPassword: ""
redisDB: 0
origins: []
